### ISSUE TITLE
Xcode better bundle resource support

### ISSUE THREAD

**Issue by attilaz** [bkaradzic/genie#39]
Bundle resources(files) are copied to target .app and they can be read at runtime.

Currently genie handles input files as resources based on file extension:
https://github.com/bkaradzic/genie/blob/master/src/actions/xcode/xcode_common.lua#L20

This means that other filetypes cannot be used runtime. 

Second problem is that currently all file is put into the root of the target app, so the app cannot reference a file like this: "meshes/cube.bin" because it will be just "cube.bin".
A solution for this could be the usage of folder references. This references add all file in that directory including subdirectories.

This could be implemented with a new option "resources" that is similar to the current "files" but handles all file as resources instead of the current extension "magic".

**Comment by Muzza** [comment]
This is an old issue, but these features were vital to my producing any Mac/iOS application so I've implemented it. It's working on Mac builds, I just want to test iOS before I do a pull request.

Note that the problem with resources being put in the root of the target app is an XCode limitation. If you refer to individual resource files, there is no way to specify the folder layout. A workaround to this is to set up a 'resource folder reference' that will grab an entire folder and package it as a resource whilst preserving the folder layout. GENie doesn't have any existing method that was suitable for setting this up so I've had to add two new tags.

To mark individual files as resources (paths will not be preserved):
```lua
files { "Folder/MyData.data", "MySrc.cpp" }
resources { "**.data" }
```

To mark an entire folder (and it's subfolders) as a resource reference (paths will be preserved):
```lua
resourcefolderrefs { "MyDataFolder" }
```

I also found that the dylib linking in xcode projects was not working. dylibs need to be both linked against and copied to the bundle to be with the executable, I fixed it to do both with this example usage:
```lua
libdirs { "Steam/133b/sdk/redistributable_bin/osx32" }
links { "steam_api" }
files { "Steam/133b/sdk/redistributable_bin/osx32/libsteam_api.dylib" }
```

**Comment by bkaradzic** [comment]
`resourcefolderrefs` <- WinRT has something similar with Package.appxmanifest and required resources. It would be the best to figure out how to unify those. I made it generate dummy resources for default setup, but didn't solve completely when resources are provided.

**Comment by Muzza** [comment]
For WinRT, I had to use file level flags to get resources to work:
```lua
enablefilelevelconfig()
configuration { "**.data" }
	flags{ "DeploymentContent", "NoLinkPath" }
```
`NoLinkPath` is a flag I added because GENie generates `<Link>` alongside `<DeploymentContent>` which does not seem to be valid. I'm not sure why `<Link>` is being emitted at all.

I would be possible to unify `resources` and the `DeploymentContent` flag, so that only one of them exists. Personally I prefer specifying the resources as a list of files rather than using the slow `enablefilelevelconfig` method, but `DeploymentContent` already exists.

I've never been able to get deployment content in WinRT projects to preserve their folder layout, so I'm not sure how `resourcefolderrefs` could be unified.
